### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by codeandroid** [cipperly/ImAnim#7]
This is a useful library - and would also come in handy in what we are doing.

Unfortunately, without a license, reuse will be severely limited (at least, if releasing something that uses this library is the plan).

Releasing the code under the MIT (or BSD) license would make adoption quite painfree.

Would you be willing to release the code under such a license?

**Comment by cipperly** [comment]
Yes, it is now MIT licensed.  Thank you for notifying me and please feel free to use however you need.
